rails_projects/test_tube/config/routes.rb
TestTube::Application.routes.draw do
  resources :line_station_news

  resources :line_station_2s

  resources :line_stations

  resources :stations

  resources :lines

end

rails_projects/test_tube/app/models/line_station.rb
class LineStation < ActiveRecord::Base
end

rails_projects/test_tube/app/controllers/line_stations_controller.rb
class LineStationsController < ApplicationController
  before_action :set_line_station, only: [:show, :edit, :update, :destroy]

  # GET /line_stations
  # GET /line_stations.json
  def index
    @line_stations = LineStation.all
  end

  # GET /line_stations/1
  # GET /line_stations/1.json
  def show
  end

  # GET /line_stations/new
  def new
    @line_station = LineStation.new
  end

  # GET /line_stations/1/edit
  def edit
  end

  # POST /line_stations
  # POST /line_stations.json
  def create
    @line_station = LineStation.new(line_station_params)

    respond_to do |format|
      if @line_station.save
        format.html { redirect_to @line_station, notice: 'Line station was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_station }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_stations/1
  # PATCH/PUT /line_stations/1.json
  def update
    respond_to do |format|
      if @line_station.update(line_station_params)
        format.html { redirect_to @line_station, notice: 'Line station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_stations/1
  # DELETE /line_stations/1.json
  def destroy
    @line_station.destroy
    respond_to do |format|
      format.html { redirect_to line_stations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_station
      @line_station = LineStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_station_params
      params.require(:line_station).permit(:line_id, :integer, :station_id, :integer)
    end
end

rails_projects/test_tube/app/helpers/line_stations_helper.rb
module LineStationsHelper
end

rails_projects/test_tube/app/views/line_stations/_form.html.erb
<%= form_for(@line_station) do |f| %>
  <% if @line_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_station.errors.count, "error") %> prohibited this line_station from being saved:</h2>

      <ul>
      <% @line_station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_id %><br>
    <%= f.text_field :line_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :station_id %><br>
    <%= f.text_field :station_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/test_tube/app/views/line_stations/edit.html.erb
<h1>Editing line_station</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_station %> |
<%= link_to 'Back', line_stations_path %>

rails_projects/test_tube/app/views/line_stations/index.html.erb
<h1>Listing line_stations</h1>

<table>
  <thead>
    <tr>
      <th>Line</th>
      <th>Integer</th>
      <th>Station</th>
      <th>Integer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_stations.each do |line_station| %>
      <tr>
        <td><%= line_station.line_id %></td>
        <td><%= line_station.integer %></td>
        <td><%= line_station.station_id %></td>
        <td><%= line_station.integer %></td>
        <td><%= link_to 'Show', line_station %></td>
        <td><%= link_to 'Edit', edit_line_station_path(line_station) %></td>
        <td><%= link_to 'Destroy', line_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line station', new_line_station_path %>

rails_projects/test_tube/app/views/line_stations/new.html.erb
<h1>New line_station</h1>

<%= render 'form' %>

<%= link_to 'Back', line_stations_path %>

rails_projects/test_tube/app/views/line_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line:</strong>
  <%= @line_station.line_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @line_station.integer %>
</p>

<p>
  <strong>Station:</strong>
  <%= @line_station.station_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @line_station.integer %>
</p>

<%= link_to 'Edit', edit_line_station_path(@line_station) %> |
<%= link_to 'Back', line_stations_path %>