rails_projects/test_tube/config/routes.rb
TestTube::Application.routes.draw do
  resources :line_station_news

  resources :line_station_2s

  resources :line_stations

  resources :stations

  resources :lines

end

rails_projects/test_tube/app/models/line_station_new.rb
class LineStationNew < ActiveRecord::Base
	belongs_to :line
	belongs_to :station
end

rails_projects/test_tube/app/controllers/line_station_news_controller.rb
class LineStationNewsController < ApplicationController
  # require 'net/http'
  before_action :set_line_station_news, only: [:show, :edit, :update, :destroy]

  # GET /line_station_news
  # GET /line_station_news.json
  def index
    @line_station_news = LineStationNew.all

    # source = "http://0.0.0.0:3000/convertcsv.json"
    # resp = Net::HTTP.get_response(URI.parse(source))
    # data = resp.body
    # results = JSON.parse(data)
  end

  # GET /line_station_news/1
  # GET /line_station_news/1.json
  def show
  end

  # GET /line_station_news/new
  def new
    @line_station_news = LineStationNew.new
  end

  # GET /line_station_news/1/edit
  def edit
  end

  # POST /line_station_news
  # POST /line_station_news.json
  def create
    @line_station_news = LineStationNew.new(line_station_news_params)

    respond_to do |format|
      if @line_station_news.save
        format.html { redirect_to @line_station_news, notice: 'Line station new was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_station_news }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_station_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_station_news/1
  # PATCH/PUT /line_station_news/1.json
  def update
    respond_to do |format|
      if @line_station_news.update(line_station_news_params)
        format.html { redirect_to @line_station_news, notice: 'Line station new was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_station_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_station_news/1
  # DELETE /line_station_news/1.json
  def destroy
    @line_station_news.destroy
    respond_to do |format|
      format.html { redirect_to line_station_news_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_station_news
      @line_station_news = LineStationNew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_station_news_params
      params.require(:line_station_news).permit(:line_id, :station_id)
    end
end

rails_projects/test_tube/app/helpers/line_station_news_helper.rb
module LineStationNewsHelper
end

rails_projects/test_tube/app/views/line_station_news/_form.html.erb
<%= form_for(@line_station_news) do |f| %>
  <% if @line_station_news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_station_news.errors.count, "error") %> prohibited this line_station_news from being saved:</h2>

      <ul>
      <% @line_station_news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_id %><br>
    <%= f.number_field :line_id %>
  </div>
  <div class="field">
    <%= f.label :station_id %><br>
    <%= f.number_field :station_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/test_tube/app/views/line_station_news/edit.html.erb
<h1>Editing line_station_news</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_station_news %> |
<%= link_to 'Back', line_station_news_path %>

rails_projects/test_tube/app/views/line_station_news/index.html.erb
<h1>Listing line_station_news</h1>

<table>
  <thead>
    <tr>
      <th>Line</th>
      <th>Station</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_station_news.each do |line_station_news| %>
      <tr>
        <td><%= line_station_news.line_id %></td>
        <td><%= line_station_news.station_id %></td>
        <td><%= link_to 'Show', line_station_news %></td>
        <td><%= link_to 'Edit', edit_line_station_news_path(line_station_news) %></td>
        <td><%= link_to 'Destroy', line_station_news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line station new', new_line_station_news_path %>

rails_projects/test_tube/app/views/line_station_news/new.html.erb
<h1>New line_station_news</h1>

<%= render 'form' %>

<%= link_to 'Back', line_station_news_path %>

rails_projects/test_tube/app/views/line_station_news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line:</strong>
  <%= @line_station_news.line_id %>
</p>

<p>
  <strong>Station:</strong>
  <%= @line_station_news.station_id %>
</p>

<%= link_to 'Edit', edit_line_station_news_path(@line_station_news) %> |
<%= link_to 'Back', line_station_news_path %>